name: Continuous Integration-FE
on:
  pull_request:
    branches:
      - main

jobs:
  continuous_integration_fe:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: List root directory contents
        run: ls -la

      - name: Navigate to frontend directory
        run: cd "bahea-cal/frontend/"

      - name: Verify package.json existence
        run: |
          if [ ! -f package.json ]; then
            echo "package.json not found in frontend directory!"
            exit 1
          fi

      - name: Install dependencies, build, and test
        run: |
          npm install
          npm run build
          npm run test
