name: Continuos Integration-FE
on:
  pull_request:
    branches:
      - main

jobs:
  continuous_integration_fe:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install dependencies, build, and test
        run: |
          npm install
          npm run build
          npm run test
