name: simple-pytest-django
on:
  pull_request:
    branches:
      ['main']

env:
  DJANGO_DEBUG: true
  DJANGO_SECRET_KEY: "django-insecure-btjo6xg-test-secret-key"
  DJANGO_ALLOWED_HOSTS: "*"
  DJANGO_BASE_URL: "http://test.localhost:8000"
  DJANGO_DATABASES__default__ENGINE: "django.db.backends.sqlite3"
  DJANGO_DATABASES__default__NAME: "db.sqlite3"
  DJANGO_ENVIRONMENT: "test"
  DJANGO_CALENDAR_NAME_PREFIX: "(test) "

jobs:
  pytest-django:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: configure python environment
        uses: actions/setup-python@v4
        with:
          python-version: '>=3.10'

      - name: install depends
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: run pytests
        run: |
          pytest
