name: simple-pytest-django
on:
  pull_request:
    branches:
      ['main']
jobs:
  pytest-django:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: configure python environment
        uses: actions/setup-python@v4
        with:
          python-version: '>=3.10'

      - name: install depends
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: run pytests
        run: |
          pytest
